-- 01_schema.sql

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = BG_OWNER;

CREATE BIGFILE TABLESPACE BiblioGuest
  DATAFILE 'BiblioGuest01.dbf'
  SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE BiblioGuestTemp
  TEMPFILE 'BiblioGuestTemp01.dbf'
  SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

ALTER USER BG_OWNER DEFAULT TABLESPACE BiblioGuest;
ALTER USER BG_OWNER QUOTA UNLIMITED ON BiblioGuest;

CREATE TABLE Areas 
    ( 
     id_area     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nombre_area VARCHAR2 (100)  NOT NULL 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

ALTER TABLE Areas 
    ADD CONSTRAINT Areas_PK PRIMARY KEY ( id_area )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Autor 
    ( 
     id_autor     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nombre       VARCHAR2 (100) , 
     apellido     VARCHAR2 (100) , 
     nacionalidad VARCHAR2 (80) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_autor_apellido_nom ON Autor 
    ( 
     apellido ASC , 
     nombre ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE Autor 
    ADD CONSTRAINT Autor_PK PRIMARY KEY ( id_autor )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Biblioteca 
    ( 
     id_biblioteca        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_normas_biblioteca NUMBER , 
     nombre               VARCHAR2 (150) , 
     id_unidad            NUMBER  NOT NULL 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_biblio_unidad ON Biblioteca 
    ( 
     id_unidad ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_biblio_normas ON Biblioteca 
    ( 
     id_normas_biblioteca ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE Biblioteca 
    ADD CONSTRAINT Biblioteca_PK PRIMARY KEY ( id_biblioteca )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE BibliotecaContacto 
    ( 
     id_biblioteca NUMBER  NOT NULL , 
     id_contacto   NUMBER  NOT NULL 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_bc_contacto ON BibliotecaContacto 
    ( 
     id_contacto ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE BibliotecaContacto 
    ADD CONSTRAINT pk_biblioteca_contacto PRIMARY KEY ( id_biblioteca, id_contacto )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Bibliotecario 
    ( 
     id_bibliotecario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nombre           VARCHAR2 (150) , 
     correo           VARCHAR2 (150) , 
     turno            VARCHAR2 (30) ,
     estado           VARCHAR2 (15) DEFAULT 'activo' ,
     password_hash    VARCHAR2 (255)
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

ALTER TABLE Bibliotecario 
    ADD CONSTRAINT Bibliotecario_PK PRIMARY KEY ( id_bibliotecario )
    USING INDEX TABLESPACE BiblioGuest ;

ALTER TABLE Bibliotecario 
    ADD CONSTRAINT uq_bibliotecario_correo UNIQUE ( correo )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Categorias 
    ( 
     id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nombre       VARCHAR2 (100) , 
     descripcion  VARCHAR2 (300) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

ALTER TABLE Categorias 
    ADD CONSTRAINT Categorias_PK PRIMARY KEY ( id_categoria )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE CategoriasLibro 
    ( 
     id_categoria NUMBER  NOT NULL , 
     id_libro     NUMBER  NOT NULL 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_cl_libro ON CategoriasLibro 
    ( 
     id_libro ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE CategoriasLibro 
    ADD CONSTRAINT pk_categorias_libro PRIMARY KEY ( id_categoria, id_libro )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Contacto 
    ( 
     id_contacto    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     tipo_contacto  VARCHAR2 (30) , 
     valor_contacto VARCHAR2 (200) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

ALTER TABLE Contacto 
    ADD CONSTRAINT Contacto_PK PRIMARY KEY ( id_contacto )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Cubiculo 
    ( 
     id_cubiculo   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     capacidad     NUMBER (3) , 
     id_biblioteca NUMBER , 
     estado        VARCHAR2 (15) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_cubiculo_biblio ON Cubiculo 
    ( 
     id_biblioteca ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_cubiculo_estado ON Cubiculo 
    ( 
     estado ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE Cubiculo 
    ADD CONSTRAINT ck_cubiculo_capacidad 
    CHECK (capacidad >= 1)
;

ALTER TABLE Cubiculo 
    ADD CONSTRAINT ck_cubiculo_estado 
    CHECK (estado IN ('disponible','ocupado','mantenimiento'))
;

ALTER TABLE Cubiculo 
    ADD CONSTRAINT Cubiculo_PK PRIMARY KEY ( id_cubiculo )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Ejemplar 
    ( 
     id_ejemplar   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_libro      NUMBER  NOT NULL , 
     codigo_barra  VARCHAR2 (50) , 
     estado        VARCHAR2 (15) , 
     id_biblioteca NUMBER 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_ejemplar_libro ON Ejemplar 
    ( 
     id_libro ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_ejemplar_biblio ON Ejemplar 
    ( 
     id_biblioteca ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_ejemplar_estado ON Ejemplar 
    ( 
     estado ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE Ejemplar 
    ADD CONSTRAINT ck_ejemplar_estado 
    CHECK (estado IN ('disponible','prestado','deteriorado'))
;

ALTER TABLE Ejemplar 
    ADD CONSTRAINT Ejemplar_PK PRIMARY KEY ( id_ejemplar )
    USING INDEX TABLESPACE BiblioGuest ;

ALTER TABLE Ejemplar 
    ADD CONSTRAINT uq_ejemplar_codigo UNIQUE ( codigo_barra )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Etiquetas 
    ( 
     id_etiqueta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nombre      VARCHAR2 (100) , 
     descripcion VARCHAR2 (300) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

ALTER TABLE Etiquetas 
    ADD CONSTRAINT Etiquetas_PK PRIMARY KEY ( id_etiqueta )
    USING INDEX TABLESPACE BiblioGuest ;

ALTER TABLE Etiquetas 
    ADD CONSTRAINT uq_etiquetas_nombre UNIQUE ( nombre )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE GrupoUsuarios 
    ( 
     id_grupo_usuarios NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

ALTER TABLE GrupoUsuarios 
    ADD CONSTRAINT GrupoUsuarios_PK PRIMARY KEY ( id_grupo_usuarios )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Laptop 
    ( 
     id_laptop         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_biblioteca     NUMBER , 
     numero_serie      VARCHAR2 (50) , 
     sistema_operativo VARCHAR2 (50) , 
     marca             VARCHAR2 (50) , 
     modelo            VARCHAR2 (80) , 
     id_utilidad       NUMBER , 
     estado            VARCHAR2 (15) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_laptop_biblio ON Laptop 
    ( 
     id_biblioteca ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_laptop_utilidad ON Laptop 
    ( 
     id_utilidad ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_laptop_estado ON Laptop 
    ( 
     estado ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE Laptop 
    ADD CONSTRAINT ck_laptop_estado 
    CHECK (estado IN ('disponible','en uso','baja'))
;

ALTER TABLE Laptop 
    ADD CONSTRAINT Laptop_PK PRIMARY KEY ( id_laptop )
    USING INDEX TABLESPACE BiblioGuest ;

ALTER TABLE Laptop 
    ADD CONSTRAINT uq_laptop_serie UNIQUE ( numero_serie )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Libro 
    ( 
     id_libro    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     isbn        VARCHAR2 (20) , 
     titulo      VARCHAR2 (300) , 
     subtitulo   VARCHAR2 (300) , 
     editorial   VARCHAR2 (150) , 
     nro_edicion NUMBER (4) , 
     anio        NUMBER (4) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_libro_titulo ON Libro 
    ( 
     titulo ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_libro_subtitulo ON Libro 
    ( 
     subtitulo ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE Libro 
    ADD CONSTRAINT Libro_PK PRIMARY KEY ( id_libro )
    USING INDEX TABLESPACE BiblioGuest ;

ALTER TABLE Libro 
    ADD CONSTRAINT uq_libro_isbn UNIQUE ( isbn )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE LibroAutor 
    ( 
     id_libro NUMBER  NOT NULL , 
     id_autor NUMBER  NOT NULL 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_la_autor ON LibroAutor 
    ( 
     id_autor ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE LibroAutor 
    ADD CONSTRAINT pk_libro_autor PRIMARY KEY ( id_libro, id_autor )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE LibroEtiquetas 
    ( 
     id_libro    NUMBER  NOT NULL , 
     id_etiqueta NUMBER  NOT NULL 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_le_etiqueta ON LibroEtiquetas 
    ( 
     id_etiqueta ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE LibroEtiquetas 
    ADD CONSTRAINT pk_libro_etiquetas PRIMARY KEY ( id_libro, id_etiqueta )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE NormasBiblioteca 
    ( 
     id_normas_biblioteca        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     dias_prestamo_libros        NUMBER (3) , 
     dias_anticipacion_libros    NUMBER (3) , 
     dias_anticipacion_cubiculos NUMBER (3) , 
     dias_anticipacion_laptops   NUMBER (3) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

ALTER TABLE NormasBiblioteca 
    ADD CONSTRAINT NormasBiblioteca_PK PRIMARY KEY ( id_normas_biblioteca )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE PrestamoLibro 
    ( 
     id_prestamo           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_usuario            NUMBER  NOT NULL , 
     id_bibliotecario      NUMBER , 
     id_ejemplar           NUMBER  NOT NULL , 
     fecha_solicitud       TIMESTAMP (0) , 
     fecha_inicio          DATE , 
     fecha_fin             DATE , 
     fecha_devolucion_real DATE , 
     estado                VARCHAR2 (15) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_prestamo_usuario ON PrestamoLibro 
    ( 
     id_usuario ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_prestamo_bibliot ON PrestamoLibro 
    ( 
     id_bibliotecario ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_prestamo_ejemplar ON PrestamoLibro 
    ( 
     id_ejemplar ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_prestamo_estado ON PrestamoLibro 
    ( 
     estado ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE PrestamoLibro 
    ADD CONSTRAINT ck_prestamo_estado 
    CHECK (estado IN ('activo','finalizado','finalizado_tardio','atrasado','cancelado'))
;

ALTER TABLE PrestamoLibro 
    ADD CONSTRAINT PrestamoLibro_PK PRIMARY KEY ( id_prestamo )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE ReservaCubiculo 
    ( 
     id_reserva        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_grupo_usuarios NUMBER  NOT NULL , 
     id_bibliotecario  NUMBER , 
     id_cubiculo       NUMBER  NOT NULL , 
     fecha_solicitud   TIMESTAMP (0) , 
     fecha_reserva     DATE , 
     hora_inicio       VARCHAR2 (5) , 
     hora_fin          VARCHAR2 (5) , 
     estado            VARCHAR2 (15) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_rc_grupo ON ReservaCubiculo 
    ( 
     id_grupo_usuarios ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_rc_bibliotecario ON ReservaCubiculo 
    ( 
     id_bibliotecario ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_rc_cubiculo ON ReservaCubiculo 
    ( 
     id_cubiculo ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_reservacubi_estado ON ReservaCubiculo 
    ( 
     estado ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE ReservaCubiculo 
  ADD CONSTRAINT ck_rc_estado
  CHECK (estado IN ('pendiente','activa','cancelada','finalizada'));

ALTER TABLE ReservaCubiculo 
    ADD CONSTRAINT ck_rc_hora_fin 
    CHECK ( REGEXP_LIKE(hora_fin, '^([01][0-9]|2[0-3]):[0-5][0-9]$') ) ENABLE;

ALTER TABLE ReservaCubiculo 
    ADD CONSTRAINT ck_rc_hora_inicio 
    CHECK ( REGEXP_LIKE(hora_inicio, '^([01][0-9]|2[0-3]):[0-5][0-9]$') ) ENABLE;

ALTER TABLE ReservaCubiculo 
    ADD CONSTRAINT ReservaCubiculo_PK PRIMARY KEY ( id_reserva )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE ReservaLaptop 
    ( 
     id_reserva       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_usuario       NUMBER  NOT NULL , 
     id_bibliotecario NUMBER , 
     id_laptop        NUMBER  NOT NULL , 
     fecha_solicitud  TIMESTAMP (0) , 
     fecha_reserva    DATE , 
     hora_inicio      VARCHAR2 (5) , 
     hora_fin         VARCHAR2 (5) , 
     estado           VARCHAR2 (15) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_rl_usuario ON ReservaLaptop 
    ( 
     id_usuario ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_rl_bibliotecario ON ReservaLaptop 
    ( 
     id_bibliotecario ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_rl_laptop ON ReservaLaptop 
    ( 
     id_laptop ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_reservalap_estado ON ReservaLaptop 
    ( 
     estado ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE ReservaLaptop 
    ADD CONSTRAINT ck_rl_estado 
    CHECK (estado IN ('activa','cancelada','finalizada'))
;

ALTER TABLE ReservaLaptop 
    ADD CONSTRAINT ck_rl_hora_fin 
    CHECK ( REGEXP_LIKE(hora_fin, '^([01][0-9]|2[0-3]):[0-5][0-9]$') ) ENABLE;

ALTER TABLE ReservaLaptop 
    ADD CONSTRAINT ck_rl_hora_inicio 
    CHECK ( REGEXP_LIKE(hora_inicio, '^([01][0-9]|2[0-3]):[0-5][0-9]$') ) ENABLE;

ALTER TABLE ReservaLaptop 
    ADD CONSTRAINT ReservaLaptop_PK PRIMARY KEY ( id_reserva )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Sancion 
    ( 
     id_sancion   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     id_usuario   NUMBER  NOT NULL , 
     motivo       VARCHAR2 (300) , 
     fecha_inicio DATE , 
     fecha_fin    DATE , 
     estado       VARCHAR2 (15) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_sancion_usuario ON Sancion 
    ( 
     id_usuario ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_sancion_estado ON Sancion 
    ( 
     estado ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE Sancion 
    ADD CONSTRAINT ck_sancion_estado 
    CHECK (estado IN ('activa','cumplida'))
;

ALTER TABLE Sancion 
    ADD CONSTRAINT Sancion_PK PRIMARY KEY ( id_sancion )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE UnidadAcademica 
    ( 
     id_unidad NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nombre    VARCHAR2 (150) , 
     tipo      VARCHAR2 (30) , 
     id_area   NUMBER , 
     id_padre  NUMBER 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_unidad_area ON UnidadAcademica 
    ( 
     id_area ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_unidad_padre ON UnidadAcademica 
    ( 
     id_padre ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE UnidadAcademica 
    ADD CONSTRAINT ck_unidad_tipo 
    CHECK (tipo IN ('Universidad','Facultad','Escuela','CentroInvestigacion'))
;

ALTER TABLE UnidadAcademica 
    ADD CONSTRAINT UnidadAcademica_PK PRIMARY KEY ( id_unidad )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE UnidadContacto 
    ( 
     id_unidad   NUMBER  NOT NULL , 
     id_contacto NUMBER  NOT NULL 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_uc_contacto ON UnidadContacto 
    ( 
     id_contacto ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE UnidadContacto 
    ADD CONSTRAINT pk_unidad_contacto PRIMARY KEY ( id_unidad, id_contacto )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE Usuario 
    ( 
     id_usuario           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nombre               VARCHAR2 (150) , 
     codigo_institucional VARCHAR2 (30) , 
     correo               VARCHAR2 (150) , 
     estado               VARCHAR2 (15) , 
     id_unidad            NUMBER 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_usuario_unidad ON Usuario 
    ( 
     id_unidad ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE Usuario 
    ADD CONSTRAINT ck_usuario_estado 
    CHECK (estado IN ('activo','sancionado','bloqueado'))
;

ALTER TABLE Usuario 
    ADD CONSTRAINT Usuario_PK PRIMARY KEY ( id_usuario )
    USING INDEX TABLESPACE BiblioGuest ;

ALTER TABLE Usuario 
    ADD CONSTRAINT uq_usuario_codigo UNIQUE ( codigo_institucional )
    USING INDEX TABLESPACE BiblioGuest ;

ALTER TABLE Usuario 
    ADD CONSTRAINT uq_usuario_correo UNIQUE ( correo )
    USING INDEX TABLESPACE BiblioGuest ;

CREATE TABLE UsuarioGrupoUsuarios 
    ( 
     id_usuario        NUMBER  NOT NULL , 
     id_grupo_usuarios NUMBER  NOT NULL ,
     estado_miembro VARCHAR2 (15) DEFAULT 'pendiente'
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

CREATE INDEX ix_ugu_usuario ON UsuarioGrupoUsuarios 
    ( 
     id_usuario ASC 
    ) 
    TABLESPACE BiblioGuest
;
CREATE INDEX ix_ugu_grupo ON UsuarioGrupoUsuarios 
    ( 
     id_grupo_usuarios ASC 
    ) 
    TABLESPACE BiblioGuest
;

ALTER TABLE UsuarioGrupoUsuarios 
    ADD CONSTRAINT pk_usuario_grupo PRIMARY KEY ( id_usuario, id_grupo_usuarios )
    USING INDEX TABLESPACE BiblioGuest ;

ALTER TABLE UsuarioGrupoUsuarios
  ADD CONSTRAINT ck_ugu_estado
  CHECK (
    estado_miembro IN ('pendiente','aceptado','rechazado')
    OR estado_miembro IS NULL
  );

CREATE TABLE Utilidad 
    ( 
     id_utilidad     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
        ( START WITH 1 NOCACHE )  NOT NULL , 
     nombre_utilidad VARCHAR2 (100) 
    ) 
    TABLESPACE BiblioGuest
    LOGGING 
;

ALTER TABLE Utilidad 
    ADD CONSTRAINT Utilidad_PK PRIMARY KEY ( id_utilidad )
    USING INDEX TABLESPACE BiblioGuest ;



ALTER TABLE BibliotecaContacto 
    ADD CONSTRAINT fk_bc_biblioteca FOREIGN KEY 
    ( 
     id_biblioteca
    ) 
    REFERENCES Biblioteca 
    ( 
     id_biblioteca
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE BibliotecaContacto 
    ADD CONSTRAINT fk_bc_contacto FOREIGN KEY 
    ( 
     id_contacto
    ) 
    REFERENCES Contacto 
    ( 
     id_contacto
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE Biblioteca 
    ADD CONSTRAINT fk_biblioteca_normas FOREIGN KEY 
    ( 
     id_normas_biblioteca
    ) 
    REFERENCES NormasBiblioteca 
    ( 
     id_normas_biblioteca
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Biblioteca 
    ADD CONSTRAINT fk_biblioteca_unidad FOREIGN KEY 
    ( 
     id_unidad
    ) 
    REFERENCES UnidadAcademica 
    ( 
     id_unidad
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE CategoriasLibro 
    ADD CONSTRAINT fk_cl_categoria FOREIGN KEY 
    ( 
     id_categoria
    ) 
    REFERENCES Categorias 
    ( 
     id_categoria
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE CategoriasLibro 
    ADD CONSTRAINT fk_cl_libro FOREIGN KEY 
    ( 
     id_libro
    ) 
    REFERENCES Libro 
    ( 
     id_libro
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE Cubiculo 
    ADD CONSTRAINT fk_cubiculo_biblio FOREIGN KEY 
    ( 
     id_biblioteca
    ) 
    REFERENCES Biblioteca 
    ( 
     id_biblioteca
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Ejemplar 
    ADD CONSTRAINT fk_ejemplar_biblio FOREIGN KEY 
    ( 
     id_biblioteca
    ) 
    REFERENCES Biblioteca 
    ( 
     id_biblioteca
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Ejemplar 
    ADD CONSTRAINT fk_ejemplar_libro FOREIGN KEY 
    ( 
     id_libro
    ) 
    REFERENCES Libro 
    ( 
     id_libro
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LibroAutor 
    ADD CONSTRAINT fk_la_autor FOREIGN KEY 
    ( 
     id_autor
    ) 
    REFERENCES Autor 
    ( 
     id_autor
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE LibroAutor 
    ADD CONSTRAINT fk_la_libro FOREIGN KEY 
    ( 
     id_libro
    ) 
    REFERENCES Libro 
    ( 
     id_libro
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE Laptop 
    ADD CONSTRAINT fk_laptop_biblio FOREIGN KEY 
    ( 
     id_biblioteca
    ) 
    REFERENCES Biblioteca 
    ( 
     id_biblioteca
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Laptop 
    ADD CONSTRAINT fk_laptop_utilidad FOREIGN KEY 
    ( 
     id_utilidad
    ) 
    REFERENCES Utilidad 
    ( 
     id_utilidad
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE LibroEtiquetas 
    ADD CONSTRAINT fk_le_etiqueta FOREIGN KEY 
    ( 
     id_etiqueta
    ) 
    REFERENCES Etiquetas 
    ( 
     id_etiqueta
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE LibroEtiquetas 
    ADD CONSTRAINT fk_le_libro FOREIGN KEY 
    ( 
     id_libro
    ) 
    REFERENCES Libro 
    ( 
     id_libro
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE PrestamoLibro 
    ADD CONSTRAINT fk_prestamo_bibliotecario FOREIGN KEY 
    ( 
     id_bibliotecario
    ) 
    REFERENCES Bibliotecario 
    ( 
     id_bibliotecario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE PrestamoLibro 
    ADD CONSTRAINT fk_prestamo_ejemplar FOREIGN KEY 
    ( 
     id_ejemplar
    ) 
    REFERENCES Ejemplar 
    ( 
     id_ejemplar
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE PrestamoLibro 
    ADD CONSTRAINT fk_prestamo_usuario FOREIGN KEY 
    ( 
     id_usuario
    ) 
    REFERENCES Usuario 
    ( 
     id_usuario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ReservaCubiculo 
    ADD CONSTRAINT fk_rc_bibliotecario FOREIGN KEY 
    ( 
     id_bibliotecario
    ) 
    REFERENCES Bibliotecario 
    ( 
     id_bibliotecario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ReservaCubiculo 
    ADD CONSTRAINT fk_rc_cubiculo FOREIGN KEY 
    ( 
     id_cubiculo
    ) 
    REFERENCES Cubiculo 
    ( 
     id_cubiculo
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ReservaCubiculo 
    ADD CONSTRAINT fk_rc_grupo FOREIGN KEY 
    ( 
     id_grupo_usuarios
    ) 
    REFERENCES GrupoUsuarios 
    ( 
     id_grupo_usuarios
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ReservaLaptop 
    ADD CONSTRAINT fk_rl_bibliotecario FOREIGN KEY 
    ( 
     id_bibliotecario
    ) 
    REFERENCES Bibliotecario 
    ( 
     id_bibliotecario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ReservaLaptop 
    ADD CONSTRAINT fk_rl_laptop FOREIGN KEY 
    ( 
     id_laptop
    ) 
    REFERENCES Laptop 
    ( 
     id_laptop
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE ReservaLaptop 
    ADD CONSTRAINT fk_rl_usuario FOREIGN KEY 
    ( 
     id_usuario
    ) 
    REFERENCES Usuario 
    ( 
     id_usuario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Sancion 
    ADD CONSTRAINT fk_sancion_usuario FOREIGN KEY 
    ( 
     id_usuario
    ) 
    REFERENCES Usuario 
    ( 
     id_usuario
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE UnidadContacto 
    ADD CONSTRAINT fk_uc_contacto FOREIGN KEY 
    ( 
     id_contacto
    ) 
    REFERENCES Contacto 
    ( 
     id_contacto
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE UnidadContacto 
    ADD CONSTRAINT fk_uc_unidad FOREIGN KEY 
    ( 
     id_unidad
    ) 
    REFERENCES UnidadAcademica 
    ( 
     id_unidad
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE UsuarioGrupoUsuarios 
    ADD CONSTRAINT fk_ugu_grupo FOREIGN KEY 
    ( 
     id_grupo_usuarios
    ) 
    REFERENCES GrupoUsuarios 
    ( 
     id_grupo_usuarios
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE UsuarioGrupoUsuarios 
    ADD CONSTRAINT fk_ugu_usuario FOREIGN KEY 
    ( 
     id_usuario
    ) 
    REFERENCES Usuario 
    ( 
     id_usuario
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;

ALTER TABLE UnidadAcademica 
    ADD CONSTRAINT fk_unidad_area FOREIGN KEY 
    ( 
     id_area
    ) 
    REFERENCES Areas 
    ( 
     id_area
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE UnidadAcademica 
    ADD CONSTRAINT fk_unidad_padre FOREIGN KEY 
    ( 
     id_padre
    ) 
    REFERENCES UnidadAcademica 
    ( 
     id_unidad
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Usuario 
    ADD CONSTRAINT fk_usuario_unidad FOREIGN KEY 
    ( 
     id_unidad
    ) 
    REFERENCES UnidadAcademica 
    ( 
     id_unidad
    ) 
    NOT DEFERRABLE 
;