-- 05_auth_schema.sql
-- Script para añadir soporte de autenticación a BiblioGuest

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = BG_OWNER;

-- ============================================================
-- 1. MODIFICAR TABLA USUARIO (Estudiantes)
-- ============================================================
-- Añadir columna password_hash para almacenar contraseña hasheada
ALTER TABLE Usuario ADD (
  password_hash VARCHAR2(255)
);

-- ============================================================
-- 2. MODIFICAR TABLA BIBLIOTECARIO
-- ============================================================
ALTER TABLE Bibliotecario ADD (
  password_hash VARCHAR2(255)
);

-- ============================================================
-- 3. CREAR TABLA ADMINISTRADOR (Nueva)
-- ============================================================
CREATE TABLE Administrador (
  id_administrador NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY 
    ( START WITH 1 NOCACHE ) NOT NULL,
  nombre           VARCHAR2(150) NOT NULL,
  correo           VARCHAR2(150) NOT NULL,
  password_hash    VARCHAR2(255) NOT NULL,
  fecha_creacion   TIMESTAMP DEFAULT SYSTIMESTAMP,
  creado_por       NUMBER  -- FK a otro Administrador (NULL para el primero)
)
TABLESPACE BiblioGuest
LOGGING;

ALTER TABLE Administrador 
  ADD CONSTRAINT Administrador_PK PRIMARY KEY ( id_administrador )
  USING INDEX TABLESPACE BiblioGuest;

ALTER TABLE Administrador 
  ADD CONSTRAINT uq_admin_correo UNIQUE ( correo )
  USING INDEX TABLESPACE BiblioGuest;

-- FK para creado_por (self-referencing)
ALTER TABLE Administrador 
  ADD CONSTRAINT fk_admin_creador FOREIGN KEY ( creado_por )
  REFERENCES Administrador ( id_administrador )
  NOT DEFERRABLE;

-- ============================================================
-- 4. ÍNDICES PARA BÚSQUEDAS DE LOGIN
-- ============================================================
CREATE INDEX ix_usuario_correo_login ON Usuario (correo)
  TABLESPACE BiblioGuest;

CREATE INDEX ix_bibliotecario_correo_login ON Bibliotecario (correo)
  TABLESPACE BiblioGuest;

CREATE INDEX ix_admin_correo_login ON Administrador (correo)
  TABLESPACE BiblioGuest;

COMMIT;
