-- 02_security.sql
ALTER SESSION SET CONTAINER = XEPDB1;

-- 1. CREAR EL ROL (El "Llavero")
CREATE ROLE BG_APP_ROLE;

-- 2. DAR PERMISOS AL ROL (Llenar el llavero)
-- Tablas principales con CRUD
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.Usuario TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.Bibliotecario TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.Administrador TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.Libro TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.Ejemplar TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.PrestamoLibro TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.ReservaLaptop TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.ReservaCubiculo TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.Sancion TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.Laptop TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.Cubiculo TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.Biblioteca TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE ON BG_OWNER.GrupoUsuarios TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.UsuarioGrupoUsuarios TO BG_APP_ROLE;

-- Tablas de catálogo con CRUD
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.Autor TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.Categorias TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.Etiquetas TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.LibroAutor TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.CategoriasLibro TO BG_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON BG_OWNER.LibroEtiquetas TO BG_APP_ROLE;

-- Tablas maestras (generalmente solo lectura)
GRANT SELECT ON BG_OWNER.Areas TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.UnidadAcademica TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.NormasBiblioteca TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.Contacto TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.Utilidad TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.BibliotecaContacto TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.UnidadContacto TO BG_APP_ROLE;

-- Permisos para ejecutar procedimientos y funciones
GRANT EXECUTE ON BG_OWNER.fn_minutos TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.fn_build_ts TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.fn_tiene_sancion_activa TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.fn_reserva_solapa_laptop TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.fn_reserva_solapa_cubiculo TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.fn_dias_atraso TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.fn_calcular_multa TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_crear_prestamo_libro TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_cancelar_prestamo_libro TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_asignar_bibliotecario_prestamo TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_devolver_prestamo_libro TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_reservar_laptop TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_cancelar_reserva_laptop TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_reservar_cubiculo TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_cancelar_reserva_cubiculo TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_confirmar_reserva_cubiculo TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_registrar_ingreso_reserva_cubiculo TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.pr_finalizar_reserva_cubiculo TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.PRC_HORARIOS_DISP_LAPTOP TO BG_APP_ROLE;

-- 3. CREAR EL USUARIO DE CONEXIÓN (El que usa Node.js)
-- Nota: Pon una contraseña fuerte aquí o pásala por variable si es posible
CREATE USER BG_CONNECT IDENTIFIED BY "bgconnect123";

-- Le damos permiso para conectarse y usar el Tablespace si necesita ordenar datos
GRANT CREATE SESSION TO BG_CONNECT;
ALTER USER BG_CONNECT QUOTA UNLIMITED ON BiblioGuest;

-- 4. ASIGNAR EL ROL AL USUARIO
GRANT BG_APP_ROLE TO BG_CONNECT;

-- 5. CREAR SINÓNIMOS (Magia para el Backend)
-- Esto permite que en tu Node.js escribas "SELECT * FROM Libro" 
-- en vez de "SELECT * FROM BG_OWNER.Libro"

-- Tablas principales
CREATE OR REPLACE SYNONYM BG_CONNECT.Usuario FOR BG_OWNER.Usuario;
CREATE OR REPLACE SYNONYM BG_CONNECT.Bibliotecario FOR BG_OWNER.Bibliotecario;
CREATE OR REPLACE SYNONYM BG_CONNECT.Administrador FOR BG_OWNER.Administrador;
CREATE OR REPLACE SYNONYM BG_CONNECT.Libro FOR BG_OWNER.Libro;
CREATE OR REPLACE SYNONYM BG_CONNECT.Ejemplar FOR BG_OWNER.Ejemplar;
CREATE OR REPLACE SYNONYM BG_CONNECT.PrestamoLibro FOR BG_OWNER.PrestamoLibro;
CREATE OR REPLACE SYNONYM BG_CONNECT.ReservaLaptop FOR BG_OWNER.ReservaLaptop;
CREATE OR REPLACE SYNONYM BG_CONNECT.ReservaCubiculo FOR BG_OWNER.ReservaCubiculo;
CREATE OR REPLACE SYNONYM BG_CONNECT.Sancion FOR BG_OWNER.Sancion;
CREATE OR REPLACE SYNONYM BG_CONNECT.Laptop FOR BG_OWNER.Laptop;
CREATE OR REPLACE SYNONYM BG_CONNECT.Cubiculo FOR BG_OWNER.Cubiculo;
CREATE OR REPLACE SYNONYM BG_CONNECT.Biblioteca FOR BG_OWNER.Biblioteca;
CREATE OR REPLACE SYNONYM BG_CONNECT.GrupoUsuarios FOR BG_OWNER.GrupoUsuarios;
CREATE OR REPLACE SYNONYM BG_CONNECT.UsuarioGrupoUsuarios FOR BG_OWNER.UsuarioGrupoUsuarios;

-- Tablas de catálogo
CREATE OR REPLACE SYNONYM BG_CONNECT.Autor FOR BG_OWNER.Autor;
CREATE OR REPLACE SYNONYM BG_CONNECT.Categorias FOR BG_OWNER.Categorias;
CREATE OR REPLACE SYNONYM BG_CONNECT.Etiquetas FOR BG_OWNER.Etiquetas;
CREATE OR REPLACE SYNONYM BG_CONNECT.LibroAutor FOR BG_OWNER.LibroAutor;
CREATE OR REPLACE SYNONYM BG_CONNECT.CategoriasLibro FOR BG_OWNER.CategoriasLibro;
CREATE OR REPLACE SYNONYM BG_CONNECT.LibroEtiquetas FOR BG_OWNER.LibroEtiquetas;

-- Tablas maestras
CREATE OR REPLACE SYNONYM BG_CONNECT.Areas FOR BG_OWNER.Areas;
CREATE OR REPLACE SYNONYM BG_CONNECT.UnidadAcademica FOR BG_OWNER.UnidadAcademica;
CREATE OR REPLACE SYNONYM BG_CONNECT.NormasBiblioteca FOR BG_OWNER.NormasBiblioteca;
CREATE OR REPLACE SYNONYM BG_CONNECT.Contacto FOR BG_OWNER.Contacto;
CREATE OR REPLACE SYNONYM BG_CONNECT.Utilidad FOR BG_OWNER.Utilidad;
CREATE OR REPLACE SYNONYM BG_CONNECT.BibliotecaContacto FOR BG_OWNER.BibliotecaContacto;
CREATE OR REPLACE SYNONYM BG_CONNECT.UnidadContacto FOR BG_OWNER.UnidadContacto;

-- Sinónimos para procedimientos y funciones
CREATE OR REPLACE SYNONYM BG_CONNECT.fn_minutos FOR BG_OWNER.fn_minutos;
CREATE OR REPLACE SYNONYM BG_CONNECT.fn_build_ts FOR BG_OWNER.fn_build_ts;
CREATE OR REPLACE SYNONYM BG_CONNECT.fn_tiene_sancion_activa FOR BG_OWNER.fn_tiene_sancion_activa;
CREATE OR REPLACE SYNONYM BG_CONNECT.fn_reserva_solapa_laptop FOR BG_OWNER.fn_reserva_solapa_laptop;
CREATE OR REPLACE SYNONYM BG_CONNECT.fn_reserva_solapa_cubiculo FOR BG_OWNER.fn_reserva_solapa_cubiculo;
CREATE OR REPLACE SYNONYM BG_CONNECT.fn_dias_atraso FOR BG_OWNER.fn_dias_atraso;
CREATE OR REPLACE SYNONYM BG_CONNECT.fn_calcular_multa FOR BG_OWNER.fn_calcular_multa;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_crear_prestamo_libro FOR BG_OWNER.pr_crear_prestamo_libro;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_cancelar_prestamo_libro FOR BG_OWNER.pr_cancelar_prestamo_libro;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_asignar_bibliotecario_prestamo FOR BG_OWNER.pr_asignar_bibliotecario_prestamo;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_devolver_prestamo_libro FOR BG_OWNER.pr_devolver_prestamo_libro;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_reservar_laptop FOR BG_OWNER.pr_reservar_laptop;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_cancelar_reserva_laptop FOR BG_OWNER.pr_cancelar_reserva_laptop;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_reservar_cubiculo FOR BG_OWNER.pr_reservar_cubiculo;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_cancelar_reserva_cubiculo FOR BG_OWNER.pr_cancelar_reserva_cubiculo;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_confirmar_reserva_cubiculo FOR BG_OWNER.pr_confirmar_reserva_cubiculo;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_registrar_ingreso_reserva_cubiculo FOR BG_OWNER.pr_registrar_ingreso_reserva_cubiculo;
CREATE OR REPLACE SYNONYM BG_CONNECT.pr_finalizar_reserva_cubiculo FOR BG_OWNER.pr_finalizar_reserva_cubiculo;
CREATE OR REPLACE SYNONYM BG_CONNECT.PRC_HORARIOS_DISP_LAPTOP FOR BG_OWNER.PRC_HORARIOS_DISP_LAPTOP;

-- ============================================================
-- 6. PERMISOS PARA VISTAS
-- ============================================================

GRANT SELECT ON BG_OWNER.VW_LIBRO_COMPLETO TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.VW_PRESTAMO_DETALLE TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.VW_RESERVA_CUBICULO_DETALLE TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.VW_RESERVA_LAPTOP_DETALLE TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.VW_SANCIONES_ACTIVAS TO BG_APP_ROLE;
GRANT SELECT ON BG_OWNER.VW_USUARIO_INVITACIONES TO BG_APP_ROLE;

-- ============================================================
-- 7. SINÓNIMOS PARA VISTAS
-- ============================================================

CREATE OR REPLACE SYNONYM BG_CONNECT.VW_LIBRO_COMPLETO FOR BG_OWNER.VW_LIBRO_COMPLETO;
CREATE OR REPLACE SYNONYM BG_CONNECT.VW_PRESTAMO_DETALLE FOR BG_OWNER.VW_PRESTAMO_DETALLE;
CREATE OR REPLACE SYNONYM BG_CONNECT.VW_RESERVA_CUBICULO_DETALLE FOR BG_OWNER.VW_RESERVA_CUBICULO_DETALLE;
CREATE OR REPLACE SYNONYM BG_CONNECT.VW_RESERVA_LAPTOP_DETALLE FOR BG_OWNER.VW_RESERVA_LAPTOP_DETALLE;
CREATE OR REPLACE SYNONYM BG_CONNECT.VW_SANCIONES_ACTIVAS FOR BG_OWNER.VW_SANCIONES_ACTIVAS;
CREATE OR REPLACE SYNONYM BG_CONNECT.VW_USUARIO_INVITACIONES FOR BG_OWNER.VW_USUARIO_INVITACIONES;

-- ============================================================
-- 8. PERMISOS PARA PACKAGES
-- ============================================================

GRANT EXECUTE ON BG_OWNER.PKG_PRESTAMOS TO BG_APP_ROLE;
GRANT EXECUTE ON BG_OWNER.PKG_RESERVAS TO BG_APP_ROLE;

-- ============================================================
-- 9. SINÓNIMOS PARA PACKAGES
-- ============================================================

CREATE OR REPLACE SYNONYM BG_CONNECT.PKG_PRESTAMOS FOR BG_OWNER.PKG_PRESTAMOS;
CREATE OR REPLACE SYNONYM BG_CONNECT.PKG_RESERVAS FOR BG_OWNER.PKG_RESERVAS;